spring:
  datasource:
    username: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut
    locations: classpath:db/migration
    sql-migration-prefix: V
    baseline-version: 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none