spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: V
    baseline-version: 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
app:
  serviceUtil:
    dateFormatter: dd/MM/yyyy
    dateTimeFormatter: dd/MM/yyyy hh:mm:ss
    bankName: Revolut
  security:
    jwt:
      secret: MySuperSecret69
      expirationMs: 86400000
  card:
    ibanPrefix: "RO18BTRL"
  client:
    restTemplate:
      connectTimeout: 69420
      readTimeout: 69420
    services:
      currency:
        baseUrl: http://localhost:3070/rates
        latestRatesEndpoint: latest
        availableCurrenciesEndpoint: availableCurrencies
  mongodb:
    databaseName: revolut
    connectionString: mongodb://localhost:27017/revolut
    userHistoryCollectionName: user_history
    cardHistoryCollectionName: card_history
    depositHistoryCollectionName: card_history
    transferHistoryCollectionName: transfer_history
server:
  port: 8088
---

spring:
  config:
    activate:
      on-profile: alexandra
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/revolut
  flyway:
    user: root
    url: jdbc:mysql://localhost:3306/revolut

---

spring:
  config:
    activate:
      on-profile: tuddi
  datasource:
    username: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut
  flyway:
    user: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut
server:
  port: 8080

---

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: appbanking079@gmail.com
    password: nyvnigfbcnjubblf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true