spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: V
    baseline-version: 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
app:
  client:
    restTemplate:
      connectTimeout: 69420
      readTimeout: 69420
    services:
      currency:
        baseUrl: http://localhost:3070/rates
        latestRatesEndpoint: latest
        availableCurrenciesEndpoint: availableCurrencies

---

spring:
  config:
    activate:
      on-profile: alexandra
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/revolut
  flyway:
    user: root
    url: jdbc:mysql://localhost:3306/revolut

---

spring:
  config:
    activate:
      on-profile: tuddi
  datasource:
    username: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut
  flyway:
    user: root
    password: tuddiroot
    url: jdbc:mysql://localhost:3306/revolut